### ISSUE TITLE
when to Discontinue / Delete Participants in Management Portal (vs REDCap)

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/RADAR-RedcapIntegration#20]
Removing from the REDCap (RC) / Management Portal(MP) happens one way in RC (delete) and two ways in the MP (delete, discontinue). If an super admin is doing this they can delete the MP record, if a regular MP user is doing this they only have the option to Discontinue. For e.g. a participant was created in RC with id=5 in MP they have a new external entry id=5 in MP, if at some point later this participant is deleted from RC and flagged in MP as "Discontinued", when the next user is created in RC it's given id=5 and the integration will fail, this is because the integration application will not created a corresponding participant in MP if one with the RC id already exists. The new user creation and integration will work once there is a free corresponding RC id in the MP. So while this is workable it needs to be documented so people don't enrol a patient if the integration has failed. My concern it the scenario, where a participant is enrolled in RC over a previous RC id of a deleted RC participant, the person doing this then doesn't realise that the integration failed (it should however be clear as the icon should only go green if successful), they may then go to the Management Portal and think the discontinued participant corresponds to the one they just tried to create -- no danger of incorrect source pairing as this is disabled on discontinued MP participants, but it may confuse)

This should be a fairly rare situation where a participant wants to exit the study and have their data removed -- in this case they should be "Deleted" in MP by a super admin and not "Discontinued" from MP. The RC record can be deleted and if a new entry is created with this RC id it shouldn't be a problem as for all intensive purposes that previous participant never existed.

And if a participant wants to no longer be part of the study but is not withdrawing their data, then these records should be left in RC and flagged as discontinued in the MP.

**Comment by afolarin** [comment]
we can make this process more robust by restricting record delete capabilities in REDCap to admins, the regular users would be able to create but not remove RC records -- which I think is basically what we want here?

**Comment by yatharthranjan** [comment]
Yes exactly, if we have same permissions on both RC and MP then this would work. They will need to contact SYS ADMINS to delete the records when a participants wants their data to be deleted (which in any case they will need to do for the historic data storage). 

Another thing we can do for now is, while creation of a subject from the integration app, if a subject already exists and has status of discontinued then we can proceed to create a new subject with the same external id. But this is not what is expected.
Ideally a subject should be deleted from MP (not discontinued) if a subject is deleted in Redcap.
Related to #15 
So yes restricting the rights to super admins in RC should work.

**Comment by nivemaham** [comment]
I agree that the permissions should be managed similarly in both components and it will avoid us having discrepancies in the data. 
But would it be possible to make-sure that we do not reuse this `id`, i.e. whenever you create a new subject(record) on Redcap, that we do not use a used identifier regardless of whether the subject is deleted or not. This is how we manage the sequencing in MP too.  This should help us to avoid this kind of scenarios. But I'm not sure whether this is achievable through redcap-integrator or via red-cap. Any idea? @yatharthranjan @afolarin

**Comment by yatharthranjan** [comment]
I think the redcap-integrator app already verifies if the subject with same external id exists and gives error if it finds it. So yes right now its not possible to have two subjects with the same external id.

**Comment by yatharthranjan** [comment]
That being said, the participant will still be created in Redcap but the integration will fail. So there will be discrepancy since now clicking on the external id url on MP will lead to this newly created record on redcap which is not what we want.
Best to restrict delete of records on both platforms to sys admins.

**Comment by nivemaham** [comment]
I understand. But my question was not about verifying the existence of a subject. it is about not using the id. 
From the description of the issue, I understand that a subject is created with `id=5`, then deleted in Redcap, but discontinued in MP. Later, when a new subject is created it is created with `id=5` since it is deleted in Redcap?. My question was not to reuse this id. i.e. when you create another subject the value should be `id=6`, even thought the subject is deleted.

**Comment by yatharthranjan** [comment]
Oh i see. I don't think that is possible on the redcap side since both systems are loosely coupled. There is no way of knowing if the subject with id 5 exists in MP when creating a subject in Redcap. The integration is triggered after the subject is created (it assigns the id on creation) and when the radar-integration form in RedCap is saved, so this is also not possible via the integration app.

**Comment by nivemaham** [comment]
Is the `id` generated from redcap or from redcap-integration-app? It does not need to know whether a subject exist in MP or not. Could it/does it know that there is/was a subject with this id?

**Comment by yatharthranjan** [comment]
The sequential id (denoted as external id in MP) is generated by redcap. There is no caching or db storage in the integration app so it does not know if the subject existed at some point in the past. It relies on data from MP api to verify the subject info.

**Comment by blootsvoets** [comment]
Two options then:
1. use a persistent identifier in redcap instead of the row number, for example add a UUID field. Redcap integrator could perhaps fill that field. The field does not have to be equal to the MP userId but it could be.
2. Add logic to create new subjects in MP if the external ID is already used. That means that multiple subjects could have the same external ID but at most one of those is allowed to be active.

**Comment by yatharthranjan** [comment]
I think restricting the users to not be allowed to delete subjects from RedCap seems sufficient here. Then the sys admins can take care of deleting the subjects from both the systems. Also this is just a rare case where participant want his/her data to be removed. Most probably, we will need to clear the raw data too in this case. So yes i would go with option 4 along with restricted rights on Redcap.

**Comment by nivemaham** [comment]
I agree with Yatharth. Similar permissions in both components work fine.

**Comment by afolarin** [comment]
But to @blootsvoets point we could also consider linking to the secondary ID in Redcap, currently the human readable I'd (if we composed it differently) or another I'd field in the the Redcap integration form even the participants uuid ciul work, but for now I think simple solution is finee
